apiVersion: apps/v1
kind: Deployment
metadata:
  name: googleclothes-deployment
  labels:
    app: googleclothes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googleclothes
  template:
    metadata:
      labels:
        app: googleclothes
    spec:
      containers:
      - name: googleclothes
        image: 809278132250.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-googleclothes:c953126adf6504d05b1f921b539ce2ee2ababd92
        ports:
        - containerPort: 80
