apiVersion: apps/v1
kind: Deployment
metadata:
  name: earphones-deployment
  labels:
    app: earphones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: earphones
  template:
    metadata:
      labels:
        app: earphones
    spec:
      containers:
      - name: earphones
        image: 809278132250.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-earphones:ef406477ca7d86f920befdd4b5472d15786c1c99
        ports:
        - containerPort: 80
