apiVersion: apps/v1
kind: Deployment
metadata:
  name: earphones-deployment
  labels:
    app: earphones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: earphones
  template:
    metadata:
      labels:
        app: earphones
    spec:
      containers:
      - name: earphones
        image: 809278132250.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-earphones:a4a46bda2192f85dc974af6dca36633ea41d627f
        ports:
        - containerPort: 80
