apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: 809278132250.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-backend:ef406477ca7d86f920befdd4b5472d15786c1c99
          ports:
            - containerPort: 5000
