apiVersion: apps/v1
kind: Deployment
metadata:
  name: electronics-deployment
  labels:
    app: electronics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: electronics
  template:
    metadata:
      labels:
        app: electronics
    spec:
      containers:
      - name: electronics
        image: 809278132250.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-electronics:a4a46bda2192f85dc974af6dca36633ea41d627f
        ports:
        - containerPort: 80
