apiVersion: apps/v1
kind: Deployment
metadata:
  name: phones-deployment
  labels:
    app: phones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phones
  template:
    metadata:
      labels:
        app: phones
    spec:
      containers:
      - name: phones
        image: 809278132250.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-phones:ef406477ca7d86f920befdd4b5472d15786c1c99
        ports:
        - containerPort: 80
