apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlegrocery-deployment
  labels:
    app: googlegrocery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlegrocery
  template:
    metadata:
      labels:
        app: googlegrocery
    spec:
      containers:
      - name: googlegrocery
        image: 809278132250.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-googlegrocery:ef406477ca7d86f920befdd4b5472d15786c1c99
        ports:
        - containerPort: 80
